Remove caveat of not supporting different directions of ordering
photocrowd/django-cursor-pagination pull request #27
Opened 2019-03-14 15:57 UTC by yeahframeoff

2019-03-14 16:50 UTC, Drarok requested changes

2019-03-14 16:50 UTC, Drarok commented on cursor_pagination.py
> +        q_acc = []
What is `q_acc` short for? Can we give it a descriptive name?

2019-03-14 16:50 UTC, Drarok commented on cursor_pagination.py
> +        return queryset.filter(filtering)
This whole block feels like it has too much whitespace – take a look at the other methods for comparison.

2019-03-14 16:50 UTC, Drarok commented on cursor_pagination.py
> +                q.update(q_eq)
Again, the variable names here make this extremely hard to follow.

2019-03-14 16:50 UTC, Drarok commented on cursor_pagination.py
> +            key_eq = "{}__exact".format(o)
`key_cmp`? `key_eq`?

2019-04-11 22:00 UTC, yeahframeoff commented
@Drarok what tests does it need so that it could be merged?

2019-05-09 19:49 UTC, cmmartti commented on cursor_pagination.py
> +        #     (field1 = value1 AND field2 = value2 OR field3 < value3).
Typo? It looks like the "OR" should be "AND".

2019-05-13 09:23 UTC, mjtamlyn commented
Hi! This looks like it has all the correct logic in place. A few thoughts:

1. Is there any performance implication in the database of the longer query structure? If so, could we drop to the tuple style code when the ordering is simpler. Some real-ish benchmarks would be useful.
2. Can we add some more tests of some more complex situations - 3 or 4 variables with some different orderings (i.e. `a, -b, -c, d`, `a, b, -c, -d` - perhaps even all permutations). Won't exercise any new code but will encourage the feeling that this works.
3. The above OR/AND comment needs updating

This should then allow us to update and merge it.

2020-10-08 05:54 UTC, nitely commented
> Is there any performance implication in the database of the longer query structure? If so, could we drop to the tuple style code when the ordering is simpler. Some real-ish benchmarks would be useful.

You can expect this query to be slower than the offset/limit approach, as it won't use the index. There is a variation that will use the index for the first field only, so it'll still be slow in most cases.

2021-12-27 17:08 UTC, AndrewIngram commented
Just bumping this because we found that there's limited utility for this library without support for mixed sort directions. We ended up vendoring this branch for internal use. This PR essentially implements the approach i've had good success with for several years.

2021-12-27 17:48 UTC, patrick91 commented
> Just bumping this because we found that there's limited utility for this library without support for mixed sort directions. We ended up vendoring this branch for internal use. This PR essentially implements the approach i've had good success with for several years.

Thanks Andrew! I'll make a not to merge this and make a new major release in the next few weeks!

2022-07-07 18:22 UTC, patrick91 commented
I'll merge this and make a release soon! sorry it took a while to get this in 😊

2022-07-07 18:22 UTC, merged